### ISSUE TITLE
Рабочий стол мигает, приложения вылетают

### ISSUE THREAD

**Issue by xlenu** [icefires-xda/replixos#5]
При открытии любого скачанного приложения, оно вылетает, рабочий стол начинает мигать, перезагрузка не помогает. ReplixOS beta 11.0 patch 2

**Comment by icefires-xda** [comment]
Здравствуйте. Вам надо включить режим разработчика двойным кликом на версию системы, открыть командную строку и вписать туда debugon, после чего перезапустить систему

**Comment by xlenu** [comment]
Спасибо, помогло
